name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: chmod +x Scripts/*.sh && ./Scripts/test.sh
      - name: Universal build
        run: ARCHS="arm64 x86_64" ./Scripts/build.sh release
